### ISSUE TITLE
v1.0.1?

### ISSUE THREAD

**Issue by spotanjo3** [Klairm/PS4-PayloadSender#1]
Can you compiled it to v1.0.1 apk? Thanks.

**Comment by Klairm** [comment]
Oh, sorry I thought it was already in the releases but it's not, thanks for letting me know, the apk is now published in the releases

**Comment by spotanjo3** [comment]
The problem is that I make my folder for an example: PS4 Payloader and put bin file in it. I dont use Downloads root because I want to use it somewhere else but your app cannot find it. It only focus on root is Downloads only. I dont like it. Can you allow it to give me a choice where my root instead ? Thanks.

**Comment by Klairm** [comment]
> The problem is that I make my folder for an example: PS4 Payloader and put bin file in it. I dont use Downloads root because I want to use it somewhere else but your app cannot find it. It only focus on root is Downloads only. I dont like it. Can you allow it to give me a choice where my root instead ? Thanks.

I'm sorry but the app calls the native system file explorer

**Comment by spotanjo3** [comment]
Thank you. I moved it and the app found it now. Thank you again.
