### ISSUE TITLE
Something is wrong with your App.

### ISSUE THREAD

**Issue by spotanjo3** [Klairm/PS4-PayloadSender#2]
Something is not right.

I used Netcat GUI on PC and bin loader from my PS4 and change to my PS4 IP address and it works fine. 

I test yours and it doesn' work. I struggle wit itt. I changed to my PS4 IP address and Port 9020 and got error message:

Alert
failed to connect to /192.168.1.43 (port 9020) from /:: (port 41155): connect failed: ETIMEDOUT (Connection timed out)

That IP address is not my PS4 IP address. I tried to changed it to mine and same error.

**Comment by Klairm** [comment]
Did you pressed the "send/enter/ok" button on the keyboard after writing your IP Address?

**Comment by spotanjo3** [comment]
Hello @Klairm I used your app for my android mobile.

**Comment by Klairm** [comment]
> Hello @Klairm I used your app for my android mobile.

Yes, but when you write on the mobile a keyboard apparears, and you have to hit the "enter/ok/send" button.

See this example 
![imagen](https://user-images.githubusercontent.com/40839469/155763012-e36c2337-2080-4b9a-9a14-703e5bb5f35d.png)
there's a return button

**Comment by spotanjo3** [comment]
You are right. But next error on PS4 message: There is not enough free memory.. repeating. NetCat from PC sent just fine. @_@

**Comment by Klairm** [comment]
> You are right. But next error on PS4 message: There is not enough free memory.. repeating. NetCat from PC sent just fine. @_@

well that's just a PS4 problem that's  a hit or miss, it happens sometimes, not a problem caused by the app

**Comment by spotanjo3** [comment]
Netcat sent immediately and works fine. That's weird but anyway.. I will keep trying. And keep you posted. Thanks. :D
